name: Web Page To Markdown
on:
    issues:
        types: [opened]
jobs:
    WebPageToMarkdown:
        runs-on: ubuntu-latest
        steps:
            - name: Does the issue need to be converted to markdown
              run: |
                  ./script/toMarkdown/DoIssueContinue.sh "${{ github.event.issue.title }}" "${{ github.event.issue.body }}"
              shell: bash
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14.16.0'
            - name: npm install
              run: npm install --production
            - name: Crawl pages and generate Markdown files
              run: |
                  node ./script/toMarkdown/index.js "${{ github.event.issue.body }}";
            - name: Git Auto Commit
              uses: stefanzweifel/git-auto-commit-action@v4.9.2
              with:
                  commit_message: '${{ github.event.issue.title }}'
                  file_pattern: chinese/articles/*.md
                  commit_user_name: PageToMarkdown Bot
                  commit_user_email: PageToMarkdown-bot@freeCodeCamp.org
